### PR TITLE
Fix ttnavigator tabbar

### PR DESCRIPTION
**Pull request by cemaleker**

### CODE REVIEW

**Comment by jverkoey** [comment]
This change is too much of a bandaid solution right now. I can quickly imagine this breaking on the iPad.

Is there a repro case to show the bug in question?

**Comment by cemaleker** [comment]
I'll try to add a repro case for tomorrow. 

There could be a better solution for this. I just needed a fast solution to release my current work, and added my result for fixing the current code here. 

For now you can delay pulling that fix. I'll try to find a better solution. I'll add my results.

**Comment by cemaleker** [comment]
Added a better solution.

Showcase for the bug can be found in repro-ttnavigator-tabbar branch at my fork.

**Comment by jwang** [comment]
scheduled for 1.0.4 release. I'll be pulling this in for testing this week.

**Comment by PabloGS** [comment]
Hey guys.. Whats the status on this and what are your findings? I've been using this fix without any issues in my apps. Can you put this into 1.0.6?

**Comment by jwang** [comment]
Hi @PabloGS - which fix are you using? The original or the updated? @cemaleker added a better solution that's not attached to this request that I want to see and make sure it's not causing iPad issues too.

**Comment by PabloGS** [comment]
The one in 48A12FF:
- (UIViewController*)topSubcontroller {
  if (self.tabBar.selectedItem == self.moreNavigationController.tabBarItem) return self.moreNavigationController;
  else return self.selectedViewController;
  }

Where can I find the better solution? I will test it if I have time.

**Comment by cemaleker** [comment]
@PabloGS this was the latest solution for problem and still being used in many applications without causing any bug. I am looking forward for this fix being pulled.

**Comment by jwang** [comment]
@cemaleker have you check it does not cause problems with the iPad per the first comment? I'll be checking that myself, but would like you to confirm as well.

**Comment by PabloGS** [comment]
Be sure to close Ticket #74 once this is pulled.
https://github.com/facebook/three20/issues/74

**Comment by jwang** [comment]
@cemaleker @PabloGS - 1.0.6 has been released. This will go into 1.0.7 for next week.

**Comment by jwang** [comment]
merged into development - 8f30e16ca74228bda9918cbb63739d27872d70f7 - release is on friday

**Pull request closed without merging**
