### PR TITLE
[extThree20CSS] suppressed variable warning

### PR DESCRIPTION
**Pull request by vguerci**
Removed variable warning, TTDINFO being compiled to nothing because of default debug level.

related to facebook/three20@c8d1155537

### CODE REVIEW

**Comment by jwang** [comment]
I haven't looked too much into the extension system, but this is very minor. I'll take a look at it. Thanks.

**Comment by diederich** [comment]
Looks good to me, too. 
John, are you going to merge this?

**Comment by vguerci** [comment]
btw, that's unrelated to extension system, that's just debug code that raise a warning since last update: facebook/three20@c8d1155

**Comment by jwang** [comment]
Yes, I am. welcome back stephan. :)

**Comment by diederich** [comment]
thanks!

**Pull request merged**
