### PR TITLE
Fixes extThree20XML warnings

### PR DESCRIPTION
**Pull request by niveuseverto**
Added delegates to extThree20XML headers to supress build time warnings

### CODE REVIEW

**Comment by diederich** [comment]
IIRC this won't work on earlier BaseSDK versions where NSXMLParserDelegate was an informal protocol. I _think_ there is proper fix somewhere else, where the protocol specification is ifdeffed.

Besides that and as one should use a BaseSDK > 4.0 anyways, I'd say add it and also fix the other occurrences?

**Comment by jverkoey** [comment]
See #521 for an availability header that allows us to put code like this within a preprocessor block.

```
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= TTIOS_4_0
@interface TTURLXMLResponse : NSObject <TTURLResponse, NSXMLParserDelegate> {
#else
@interface TTURLXMLResponse : NSObject <TTURLResponse> {
#endif
```

**Comment by jverkoey** [comment]
After talking with diederich about this, we've decided that we're not going to continue supporting pre-iOS 4 SDKs for simplicity's sake. We'll still support iOS 3.0 as the minimum SDK in the runtime, but we make no promises that you'll be able to build newer versions of Three20 on versions of Xcode pre 3.2.5.

**Comment by jwang** [comment]
be careful with adding commits to a pull request branch. things can get a bit nasty on some items.

**Pull request closed without merging**
