### PR TITLE
TTTableSettingsItemCell class

### PR DESCRIPTION
**Pull request by aporat**
added `TTTableSettingsItem` & `TTTableSettingsItemCell` which emulate the style of `UITableViewCellStyleValue1` (standard iOS settings table cell). This is really useful and good table cell style which needs no style adjustments. 

The `TTTableSettingsItemCell` class uses the `UITableViewCellStyleValue1` style directly.

### CODE REVIEW

**Comment by jwang** [comment]
Can you add an example of it's use to TTCatalog too?

**Comment by aporat** [comment]
yeah, it's already there in the table items demo

**Comment by jwang** [comment]
sweet. Thanks!

**Comment by tszming** [comment]
Also searching for this style for a while, +1 for merging into master.

**Comment by aporat** [comment]
the feature is already on the development branch (however not released to the master branch). you can grab it by cloning the github repo and switch to the development branch

**Comment by tszming** [comment]
Yes, just wondering since the last merge to master was back to Sept..

**Pull request merged**
