### PR TITLE
Fix for -all_load -force_load

### PR DESCRIPTION
**Pull request by echamberlain**
This replaces pull request #421.

The changes have been cleaned up to fit the Three20 styling.

### CODE REVIEW

**Comment by vguerci** [comment]
doesnt really matter but that's **Y**AJL and not JAJL

**Comment by jverkoey** [comment]
I have a few additional modifications to make to this pull request concerning removing the -force_load flags from each of the sample apps. Let's do this:
1. Can I get you to squash the spelling error into the previous commit and then force push your branch?
2. Once that's done, I'll issue a pull request to you on top of your `Categories` branch. If you could review the changes I've made and do the following from your branch we'll be rocking:
   
      git checkout Categories-samples
      # Review the changes
      git checkout Categories
      git rebase Categories-samples
      git branch -D Categories-samples
      git push origin Categories

This will push my new changes back to this pull request and then we can do one final run-through of reviews.

**Comment by echamberlain** [comment]
I'm new to git.

Where is Categories-samples?

**Comment by jverkoey** [comment]
I'm going to issue a pull request to your repo once you've squashed your commit, so it doesn't exist yet.

Here's the easiest way to squash your commit:

```
git checkout Categories
git rebase -i HEAD^^
# Interactive rebase on the last two commits. When the editor appears
# showing the last two commits, replace the word `pick` on the last
# commit with the letter `s` for `squash`. Save the editor and close it,
# and git will squash that commit onto the previous commit. It will then
# ask you to update the commit message. In this case, you can simply
# remove the second commit message because we don't need it anymore.
git push origin Categories --force
```

**Comment by vguerci** [comment]
that's the point 2. he's waiting for you to do 1. :)
I guess he cleaned all the xcconfig files from -all_load / -force_load :)

**Comment by echamberlain** [comment]
I understand now.

The rebase is done.

**Comment by jverkoey** [comment]
Looks good! I'll fire off my pull request now.

**Comment by echamberlain** [comment]
I've pulled and pushed the samples.

**Comment by jverkoey** [comment]
Awesome. I'll do some quick testing to make sure everything builds fine. If everyone on this pull request could verify that this branch works fine with their own projects, that would be awesome :)

**Comment by vguerci** [comment]
I was doing exactly the same changes when I received these comments notifications.
Got exactly the same resulting diff, except that I cleaned unused variables :`*_LIB` and `OBJC_ALLLOAD` in `Librairies.xcconfig` and also one `OBJC_ALLLOAD` in `samples/common/Configurations/Unitests.xcconfig`
And I confirm it works on an own project I'm currently working on.

**Comment by jverkoey** [comment]
Merge branch &#39;echamberlain-Categories&#39; into development

Closed by 13e84400133c11eca31ecf97680f7484de0a48a5.

**Comment by jverkoey** [comment]
Nice work everyone, thanks for pulling this awesome change together! It'll really simplify a lot of people's lives.

**Pull request closed without merging**
