### PR TITLE
Fix TTURLRequest when POSTing files

### PR DESCRIPTION
**Pull request by rogchap**
1. I've added support for naming the file parameter name separately from the filename in a generatePostBody. 
2. I've also removed the first beginLine in generatePostBody as this was returning a HTTP error 400, and I could not see a need for it being there.

### CODE REVIEW

**Comment by rogchap** [comment]
FYI....don't know why I typed "port" when I really mean "post" :)

**Comment by rogchap** [comment]
I've split out the new functionality so this should make sure it doesn't break current implementation.

**Comment by RafaelAlba** [comment]
I tried using this patch in my fork of three20 and it seems to break all requests. The removal of this line seems to be the culprit(adding it back in there fixed the issue):
-    [body appendData:[[NSString stringWithFormat:@"--%@\r\n", kStringBoundary]  
-       dataUsingEncoding:NSUTF8StringEncoding]];

**Comment by hongrich** [comment]
I believe the removal of those lines are what fixes the issues when POSTing files. I have not tried this patch directly, but I did remove those 2 lines just to fix the problem with POSTing files.

Could you try just remove those 2 lines but not use the rest of the patch to see if things still work?

**Comment by rogchap** [comment]
@RafaelAlba What errors are you getting? I'm using this patch in all my applications that use both GET and POST requests with no issues.

**Comment by RafaelAlba** [comment]
I removed those lines and the server fails with a 500 error, but with them there everything works fine. I'll have to check the exact error on the server tomorrow when I'm back in the office.

The server is running rails 3.x.

**Comment by rogchap** [comment]
Are you getting the 500 on GET requests or is it only POST requests? What web server are you using to run Rails? Apache or Nginx (with Passenger)?

**Comment by RafaelAlba** [comment]
Sorry about the long delay. Checking into this again. We're using nginx with passenger. The error in the logs is:

EOFError (bad content body).

It's happening on POSTs not sure about GETs just yet.

**Comment by RafaelAlba** [comment]
Ok, only fails on POST requests

**Comment by rogchap** [comment]
I've tested this and it seems that it is web server specific: 

When testing with IIS it fails with the extra boundary and succeeds without it, and Nginx seems to be the opposite: ie falis without the extra boundary and succeeds with the boundary line.

I need to understand more about post data / multipart forms / boundary to figure this one out.

**Comment by jwang** [comment]
@rogchap can you update to development branch and resolve the conflicts accordingly? Also, not sure if and how you can deal with @RafaelAlba's issue of failing POST.

**Comment by rogchap** [comment]
I'll update.

Not sure what to do on the POST problem. I've spent quite a lot of time on comparing "post"s from regular website form vs three20 (or any iOS project) using web proxies to check on the requests etc. I'm sure the extra boundary is wrong.

**Comment by jwang** [comment]
Hey @rogchap - I'm going to push this off for next release. I want to test it a bit more as I'm concerned about it breaking existing implemention, though I think you already addressed that. I have 2 more items I want to push out today and tomorrow then will release. I'll put this into next week's release.

**Comment by hongrich** [comment]
The boundary problem seem to have already been fixed in this commit abd35ca04a0c9e4f95bf9c22c55ee191ae086316

**Comment by jwang** [comment]
Thanks @hongrich :)

**Comment by jamesgpearce** [comment]
Facebook has not maintained or supported Three20 for some time, and we are closing its old and outstanding pull requests.

Many, many thanks for your support of the project. If you have any further questions, please don't hesitate to let me know.

**Pull request closed without merging**
