### PR TITLE
Xcode4 ttmodule support

### PR DESCRIPTION
**Pull request by taknology**
Xcode4 ttmodule support

### CODE REVIEW

**Comment by jverkoey** [comment]
Nailed it.

**Comment by taknology** [comment]
Wow.  Ok. I'm really not getting the hang of this Git SCC.  I'm afraid to commit the other changes now :).

**Comment by jverkoey** [comment]
Just do the same process of creating a branch for each pull request you want to make and pushing that.

So let's say you have a another commit you want to review:

```
git checkout origin/development
git checkout -b my-fix-name
git cherry-pick sha1
```

In my setup, each of my projects has its own branch. So for the github demo I'm building, I have a "github" branch that's based off of development. Whenever development gets updated, I simply do `git checkout github; git rebase development` to get it up-to-speed.

For features and bug fixes, they'll usually be in one of my project branches, so when I want to get them ready for review I cherry-pick them into a new branch on development (like above) and submit that for review.

**Comment by alhafoudh** [comment]
Does it work with Xcode4 GM 2? I am having header search path problem. Is it only me?

**Comment by jwang** [comment]
It works fine for GM 2.

**Comment by jwang** [comment]
I'll test this out a bit more this week then if it passes, merge it in.

**Comment by rogchap** [comment]
+1 for merge Xcode4 is now released!

**Comment by jwang** [comment]
Closed by a8787dc95d2e50ac111f49c75a381b6852100b27.

**Pull request closed without merging**
