### PR TITLE
Fix issue 361

### PR DESCRIPTION
**Pull request by mmorearty**
Pull request that fixes facebook/three20#361 -- please see that issue for a full description and discussion.

### CODE REVIEW

**Comment by jwang** [comment]
scheduled for 1.0.4 release. I'll be pulling this in for testing this week.

**Comment by jverkoey** [comment]
Ping for merging this one. Would you still like to grab it jwang?

Looks really sound, thanks for the detailed breakdown mmorearty!

**Comment by jwang** [comment]
yea. i'll bring it in tomorrow morning.

**Comment by jwang** [comment]
merged via commit 8348ce7d3b4bb240ed9bdfdbc9fdadddd8e361b4

**Pull request closed without merging**
