### PR TITLE
TTTableViewCell Text Cut Off when the DisclosureIndicator is Displayed

### PR DESCRIPTION
**Pull request by phillipuniverse**
The discussion is on the forums: http://forums.three20.info/discussion/37/bug-found-ttcaptionitemcell-cuts-off-text

### CODE REVIEW

**Comment by esilverberg** [comment]
FWIW I can confirm this is a bug and that the recommended code change fixes this issue.

**Comment by jwang** [comment]
What changed in project.pbxproj? I'm hoping nothing and that was just minor.

**Comment by phillipuniverse** [comment]
Hmm good question I'm not sure how that one snuck in there.  Can I modify the pull request to take that out?  It looked like a Three20UICommonUnitTests target got stuck in there inadvertently.  It's not needed at all.

**Comment by jwang** [comment]
no worries, just checking. I'll manually deal with it.

**Comment by jverkoey** [comment]
I have a fix for this already that recycles code a bit better. #527.

**Pull request closed without merging**
