### PR TITLE
Support sending application/x-www-form-urlencoded forms 

### PR DESCRIPTION
**Pull request by jdewind**
Currently the TTURLRequest always submits a POST using multipart/form content type in order to support data and images out of the box. However, there are times when this is not necessary (most of the time) and some APIs stipulate the "Content Type" for a particular request -- returning an error if the content type is not respected.

This pull request contains a small set of changes that allows a URL request to be configured with a non "multipart" post body. By default, the request is multipart in order to be inline with the current expectations of a POST under TTURLRequest  -- which is every post contains a multipart/form body.

For example,

  TTURLRequest *urlRequest = [[[TTURLRequest alloc] initWithURL:@"http://www.google.com" delegate:nil] autorelease];

  [urlRequest setHttpMethod:@"POST"];

  urlRequest.multiPartForm = NO;

I have tests for these changes. However, I wrote them using a different test framework. The gist can be found [here](https://gist.github.com/823018).

### CODE REVIEW

**Comment by jwang** [comment]
Looks like there's still some conflicts going on with the latest development branch. I'm going to release 1.0.6 soon. Release Candidate is going out in about 5-10 minutes to the Google Group. If you can get it all sorted out, I can include it in the 1.0.6 release for Wednesday, pending any issues that come up with the RC version.

**Comment by jdewind** [comment]
It was a small conflict (initializer). Should be resolved. I've been a merge maniac (it is weird to merge remotes outside of your fork).

**Comment by jwang** [comment]
Awesome! Thanks! Totally understandable. This is one of the better docs I've found to keep things updated for my own projects.

http://robots.thoughtbot.com/post/5133345960/keeping-a-git-fork-updated

**Comment by jdewind** [comment]
@jwang Thanks, that is a good technique to manage remote branches outside of your own fork.

**Comment by jwang** [comment]
@dewind - merged into 1.0.6 RC please validate state and report back. Thanks! :)

**Comment by jdewind** [comment]
Looks good!

**Comment by jwang** [comment]
Thanks @dewind! :)

**Pull request merged**
