### PR TITLE
[Localization] Added Hebrew (he) localization

### PR DESCRIPTION
**Pull request by aporat**
Adds basic Hebrew localization 

Closes #504

### CODE REVIEW

**Comment by jwang** [comment]
[Bundle] - Tag as Localization

That's a note, because tagging of pull requests has disappeared for some reason.

**Comment by aporat** [comment]
You mean the tag of the pull? אין בעיה

**Comment by jwang** [comment]
we can tag issues. If you look at the [Issues tab](https://github.com/facebook/three20/issues), you'll see a bunch of tags. We try to do the same for Pull Requests as they're also "Issues" but that seems to have changed recently. Until I can figure out how to do that again, I'm just writing in some notes in the comments.

**Comment by aporat** [comment]
I added the tag, but its just jumps back here. is that what you mean?

**Comment by jwang** [comment]
don't worry about it. It's just internal for us to keep things organized. :)

**Comment by jverkoey** [comment]
Asking internally at Facebook to get someone to verify this commit.

**Comment by jverkoey** [comment]
Someone should be looking at this in the next couple of days. Thanks for submitting this aporat :)

**Comment by aporat** [comment]
Great, i dont know why, but the preview here can't read the localized file correctly. (I have checked with the itailan translation and it's looks gibberish as well)

Here is the file after copying it out from the bundle:

"%d hours ago" = "לפני %d שעות";

"%d minutes ago" = "לפני %d דקות";

/\* Current page in photo browser (1 of 10) */
"%d of %d" = "%1$d מתוך %2$d";

"%d seconds ago" = "לפני %d שניות";

/\* Date format: 3d */
"%dd" = "%dd";

/\* Date format: 3h */
"%dh" = "%dh";

/\* Date format: 50m */
"%dm" = "%dm";

/\* Date format: less than one minute ago */
"<1m" = "<1m";

"Alert" = "אזהרה";

"Are you sure you want to cancel?" = "האם אתה בטוח שאתה רוצה לבטל?";

"Cancel" = "ביטול";

"Connection Error" = "שגיאת חיבור";

"Connection Timed Out" = "חיבור לא הושג";

"Done" = "סיום";

/\* Date format: Mon 1:05 pm */
"EEE h:mm a" = "EEE h:mm a";

/\* Date format: Monday */
"EEEE" = "EEEE";

/\* Date format: Monday, July 27, 2009 */
"EEEE, LLLL d, YYYY" = "EEEE, LLLL d, YYYY";

"Error" = "שגיאה";

"Load More Photos..." = "טען עוד תמונות...";

"Loading..." = "טוען...";

/\* Date format: 7/27/09 */
"M/d/yy" = "M/d/yy";

/\* Date format: Jul 27 1:05 pm */
"MMM d h:mm a" = "MMM d h:mm a";

/\* Date format: July */
"MMMM" = "MMMM";

/\* Date format: July 27 */
"MMMM d" = "MMMM d";

"New Message" = "הודעה חדשה";

"No" = "לא";

"No Internet Connection" = "אין חיבור אינטרנט";

"No Photos" = "אין תמונות";

"OK" = "OK";

"Ok" = "Ok";

"Open in Safari" = "פתח ב- Safari";

/\* Title for back button that returns to photo browser */
"Photo" = "תמונה";

"Post" = "פרסם";

"Search" = "חיפוש";

/\* See all photo thumbnails */
"See All" = "הראה הכל";

"Send" = "שלח";

"Sending..." = "שולח...";

"Showing %@ Photos" = "מראה %@ תמונות";

"Showing %@ of %@ Photos" = "מראה %1$@ מתוך %2$@ תמונות";

"Sorry, there was an error." = "מצטערים, שגיאה התרחשה.";

"Subject:" = "נושא:";

"This photo set contains no photos." = "אוסף התמונות אינו מכיל תמונות.";

"To:" = "אל:";

"Today" = "היום";

"Unable to load this photo set." = "נכשל בטעינת אוסף התמונות.";

"Updating..." = "מעדכן...";

"Yes" = "כן";

"Yesterday" = "אתמול";

"about a minute ago" = "בערך לפני דקה";

"about an hour ago" = "בערך לפני שעה";

/\* Date format: 1:05 pm */
"h:mm a" = "h:mm a";

"just a moment ago" = "לפני רגע";

/\* Date format: 2009 */
"yyyy" = "yyyy";

**Comment by jverkoey** [comment]
Cool, that helps a lot :)

**Comment by jverkoey** [comment]
Just heard back from the localization team. They only have a few requests for changes:

```
"Alert" = "התראה"
"Connection Timed Out" = "הזמן שהוקצב לחיבור הסתיים"
"OK" = "אישור"
"Sorry, there was an error" = "מצטערים, אירעה שגיאה"
```

**Comment by jverkoey** [comment]
Let me know if anything didn't copy correctly. If you could make those changes in a new commit and push them to your `bundle-hebrew-translation` branch, that'd be perfect :)

**Comment by aporat** [comment]
okay, I committed those changes from the localization team

**Comment by jverkoey** [comment]
Sweet.

**Pull request merged**
