### PR TITLE
[extJSON] updated JSON library to version 3.0

### PR DESCRIPTION
**Pull request by aporat**
I had to update the three20's json library in order to use another external library in one of my projects.

This update doesn't seem to effect the twitter sample app, so I assume it's fully backward compatibility.

### CODE REVIEW

**Comment by jwang** [comment]
@aporat Was there a difference between this and #596? Also, see my note on #563? I'm going to release 1.0.6 RC today for testing.

**Comment by aporat** [comment]
I included some extra commits in #596 that aren't related, so I closed that pull and requested another one

**Comment by jwang** [comment]
Cool. Thanks!

**Comment by diederich** [comment]
Hm, this doesn't seem to be version 3.0 but some earlier beta of the 3.0 branch.

I'm getting quite some warnings (shadowed parameters, - errorTracefrom not found) this one, anyone else sees them?

Edit: see #618

**Comment by diederich** [comment]
also, there now seems to be a duplicate category on NSObject, one which probably crashes on errors:
NSObject+SBJSON.m (old, crashes on error when calling errorTrace) and NSObject+JSON.m (current)

**Comment by diederich** [comment]
see #626 for an update

**Pull request merged**
