### PR TITLE
New High-Res default picture for Photos.app

### PR DESCRIPTION
**Pull request by steipete**

### CODE REVIEW

**Comment by jverkoey** [comment]
Hot. Are we allowed to use these images?

**Comment by steipete** [comment]
I guess so. Those are extracted from UIKit, the same as Photos.app uses internally.
IANAL but as long as this library is iOS only, it shouldn't be a problem.

**Comment by jwang** [comment]
Will check on the licensing about this and let get back to it.

**Comment by jwang** [comment]
It looks like it should be fine as long as we include the license from Apple - https://gist.github.com/830118

Granted, Apple does sort of hide these in UIKit from the public, but there are extractors out there. I think we may be better off just making a high res version of our current image for now.

**Comment by steipete** [comment]
too bad, but thanks for the info.

**Pull request closed without merging**
