### PR TITLE
Removal of hard-coded mappings of TTTableItems to TTTableViewCells

### PR DESCRIPTION
**Pull request by aptogo**
I've made the following changes to make it easier to create new TTTableItem subclasses and/or TTTableViewCell subclasses:

TTTableViewDataSource now delegates to each TTTableItem to determine what type of TTTableViewCell to create or dequeue instead of the hard-coded associations in TTTableViewDataSource:tableView:cellClassForObject:. This means that TTTableViewDataSource does not have to be subclassed to add new hard-coded mappings in tableView:cellClassForObject: when you want to add a new type of TTTableItem.

Delegation to TTTableItem also opens up the possibility of dynamically creating different associated TTTableViewCells based on TTTableItem properties.

Note that non-TTTableItem-derived list items are still handled as a special case.

### CODE REVIEW

**Comment by jdg** [comment]
+1 nice work.  This would be super handy!

**Comment by aptogo** [comment]
Include commit 23d62dc if you do a pull. I broke TThumbsViewController - fixed now

**Comment by jverkoey** [comment]
This looks good. I'll test it out.

**Comment by dwery** [comment]
Seems pretty nice, I'd love to have it included!

**Comment by diederich** [comment]
Looks good!
I've added a few more commits on top of this here:
https://github.com/diederich/three20/commits/three20-remove-hard-coded-cell-mapping

changes:
- setObject was called multiple times if cell was just created
- extracted the item->cell mapping into a protocol, so simple model objects can directly implement it
- throw an exception if - cellClass on TTTableItem is called.

I think the exception might be a good idea. Say we add this pull request and devs update their three20 version. All the their custom TableItems which were derived from TTTableItem _seem_ to work properly, but instead they're just creating plain TTTableCells instead of the custom mapping they had installed before. This is likely a programming error thus the exception.

## Rambling

I have a bit a bad feeling about the dependencies create here: the TableItem has to know the TableCell and the TableCell has to know about the TableItem. This looks quite circular :/
Maybe we're asking the wrong object about creation of the cell? 
I think the whole idea on the tableitem -> cell mapping was, that there can be generic/reusable TableViewDataSources. The hardcoded mapping prevents this, thus a different object has to be asked about which cell to create for an item. Other options that come to mind:
- create a loose mapping, e.g. something like the navigator ([ItemCellMapper map:[MyItem class] toCell:[MyCell class]])
- ask the controller

**Comment by jwang** [comment]
scheduled for 1.0.4 release. I'll be pulling this in for testing this week.

**Comment by diederich** [comment]
I'm using this in one of my projects and it works well. 
Still, I have a bit of a bad feeling about it. See the rambling above. We might wanna discuss this on the public ML. Maybe others have some ideas about it, too?

**Comment by dwery** [comment]
Cells and Items are tightly bound to each other. It makes sense to me that they both know their counterpart.

**Comment by jamesgpearce** [comment]
Facebook has not maintained or supported Three20 for some time, and we are closing its old and outstanding pull requests.

Many, many thanks for your support of the project. If you have any further questions, please don't hesitate to let me know.

**Pull request closed without merging**
