### PR TITLE
Xcode 4 support for ttmodule.py

### PR DESCRIPTION
**Pull request by taknology**
Updated Pbxproj.py to work with Xcode 4. Retained backward compatibility with Xcode 3.

### CODE REVIEW

**Comment by jverkoey** [comment]
Careful when you issue pull requests from master. In this case your new commits got added to this pull request. Can you change the source commit to 71ad497 so that this pull request only shows that one?

**Comment by jverkoey** [comment]
Can you resubmit this pull request so that the correct commits are here?

**Comment by taknology** [comment]
Hi Jeff,

I will try to do that tomorrow for these commits.  I'm working toward a hard deadline and it's approaching way too fast.

Thanks
Tony

**Comment by jverkoey** [comment]
No problem, thanks for putting these together :)

**Comment by taknology** [comment]
You're very welcome. I'm glad to give something back to such a great project.

**Comment by taknology** [comment]
Hi Jeff. I have added a new pull request for this file change from the development branch of my fork. If you could have a look and let me know if I have done this right this time that would be great.  I'll wait for confirmation before I do my other two changes.

Thanks,
Tony

**Pull request closed without merging**
