### PR TITLE
Fix Clang Compiler warnings

### PR DESCRIPTION
**Pull request by steipete**
fixes all those "expression result unused" errors when building with clang.
Fixed that by declaring the variables explicitly and adding a #pragma unused.

### CODE REVIEW

**Comment by jwang** [comment]
You ran into these with the new 1.0.3 release? I thought I saw some commits that went in to resolve this. Thanks.

**Comment by jverkoey** [comment]
I didn't clean up all the `self.view` calls because they tease at some larger design flaws with the library. Many of the controllers were written with the data and view components tightly bound together, so to properly fix the `self.view` warnings would require a good, concentrated look at each controller in question.

**Comment by jverkoey** [comment]
I'm going to close this pull request for now because of the mentioned design issues above, but it does sound like we should make it more clear how to change the active compiler in Three20.

**Comment by jverkoey** [comment]
Thanks for tackling this though steipete :)

**Comment by steipete** [comment]
So Jeff, basically, you're keeping the warnings because they are by design?  (only talking about d61bcaf now)
With changing them to explicit variables it's much more clear that those calls actually DO something IMHO.

cheers,
Peter

**Comment by jverkoey** [comment]
That's a fair point. My intention in keeping them was that they make it pretty clear where the problems are in the controllers. That being said, the merit of being warning-free isn't completely lost on me.

What do you think?

**Comment by steipete** [comment]
I'd vote for being warning-free, I treat warnings as errors and they obviously are more than annoying then.
But it should be documented that this is because of design flaws .

**Comment by jverkoey** [comment]
Let's merge this in then. What do you think is the best way to document the design issue?

**Comment by steipete** [comment]
a one-liner prior those "hacks" with an short note and an url

**Comment by jwang** [comment]
We need to document the design issue internally as well so we can fix it in the long term. I'm all for being warning free, but we need to document it properly and not forget about fixing the underlying issue in the future.

**Comment by jwang** [comment]
Closing this as it is really messy right now. I think I've addressed most of these now. I'll jump around and fix the rest as I run into them.

**Comment by steipete** [comment]
Yea, you did lots of progress, great job!

**Pull request closed without merging**
