### PR TITLE
update SBJson to 3.0.2

### PR DESCRIPTION
**Pull request by diederich**
updates SBJson from 3.0betaX to 3.0.2 (removes obsolete files)
see #597 and #618

### CODE REVIEW

**Comment by diederich** [comment]
This pull request has 2 different warnings:

[...]/three20/src/extThree20JSON/Vendors/JSON/SBJsonTokeniser.m:325: warning: declaration of 'exp' shadows a global declaration

/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS4.3.sdk/usr/include/architecture/arm/math.h:247: warning: shadowed declaration is here

see https://github.com/stig/json-framework/blob/master/Classes/SBJsonTokeniser.m#L325

Maybe it should be changed to something like 'explicit_exponent'? (@stig)

**Comment by stig** [comment]
Yah, I'll fix that.

Very meta/recursive: https://github.com/stig/json-framework/issues/89

**Comment by diederich** [comment]
stig, thanks :)

**Comment by diederich** [comment]
Closing this - #636 does the same and also fixes TTExtensionLoader.m

**Pull request closed without merging**
