### PR TITLE
Fix TTPostController showInView:animated: to call superController's viewWillDisappear: and viewDidDisappear: methods.

### PR DESCRIPTION
**Pull request by echamberlain**
TTPostController should call the parent view's viewWillDisappear: and viewDidDisappear: methods when showInView:animated: is invoked.

### CODE REVIEW

**Comment by jwang** [comment]
Thanks! Simple enough. Will check why it wasn't calling it.

**Comment by echamberlain** [comment]
Nevermind, I figured it out.

I'm going to close this pull request, fix the code, and submit a new one based off of development.

**Comment by jverkoey** [comment]
Cool. The viewDidDisappear method should be called only once the view has completely been hidden as per the Apple Docs.

http://snaapi.com/iPhone/UIViewController%20viewDidDisappear:

**Comment by echamberlain** [comment]
This pull request was replaced by pull request #436.

**Pull request closed without merging**
