### PR TITLE
Support for sections with footer text in TTSectionedDataSource  

### PR DESCRIPTION
**Pull request by aporat**
This change adds the ability to have custom footer text in table view sections.

A `TTSectionedDataSource` section can be either a standard `NSString` or a `TTTableSection` object. The section object can be used to set both header & footer text (or any combination of the two). 

`TTTableSection` class has one helper function which is used create sections, similar to the behavior of `TTTableItem`:

`[TTTableSection sectionWithHeaderTitle:@"Header Text" footerTitle:@"Footer Text"]`

See the modified TTCatalog with some examples.

### CODE REVIEW

**Comment by jwang** [comment]
@aporat can you check the conflicts and resolve them? It's likely project.pbxproj again.

**Comment by aporat** [comment]
sure, i have no idea how to solve conflicts in git, so i'll just resubmit the pull request against the latest development branch

**Comment by jwang** [comment]
ok. can you put a comment in here when you're done with the new :octocat: issue number? Thanks!

**Comment by aporat** [comment]
I tried to rebase the branch. can you try to merge it now? hopefully it did something..

**Comment by aporat** [comment]
haha, well, i guess it didn't work.

**Comment by aporat** [comment]
duplicate of https://github.com/facebook/three20/pull/693

**Pull request closed without merging**
