### PR TITLE
Removing build warnings

### PR DESCRIPTION
**Pull request by yosit**
three20 includes 27 build warning out of the box - this commit removes most of them.

### CODE REVIEW

**Comment by aporat** [comment]
that's cool, i hate those build warning too :-) 

can you target the development branch instead and remove the unrelated cache size fix?

**Comment by phillipuniverse** [comment]
Shouldn't all the self.view change to [self getView] instead of [self view]?

**Comment by phillipuniverse** [comment]
Also, I think pull requests should be based against dev, not master

**Comment by yosit** [comment]
No, I think you are confusing It with setters. Getters don't have a get in
front .

Yosi Taguri | Co-Founder | Labgoo | iPhone: http://ahhhpah.com | twitter:
http://twitter.com/yosit | Mobile: +972-544-816020 | Google Voice: +1 (415)
935-1126  | Email: yosi@taguri.com

On 30 בנוב 2011, at 00:51, Phillip Verheyden <
reply@reply.github.com>
wrote:

Shouldn't all the self.view change to [self getView] instead of [self view]?

---

**Comment by yosit** [comment]
Yes, will fix that tomorrow

Yosi Taguri | Co-Founder | Labgoo | iPhone: http://ahhhpah.com |
twitter: http://twitter.com/yosit | Mobile: +972-544-816020 | Google
Voice: +1 (415) 935-1126  | Email: yosi@taguri.com

On 30 בנוב 2011, at 00:52, Phillip Verheyden
reply@reply.github.com
wrote:

**Comment by phillipuniverse** [comment]
Ah you're right; my mistake.  This is great by the way; thanks for taking the time to contribute!

**Pull request closed without merging**
