### PR TITLE
Three20 CSS Extension New Design and TTImageViewDelegate improvements.

### PR DESCRIPTION
**Pull request by seqoy**
A lot of improvements. See commits.

### CODE REVIEW

**Comment by jwang** [comment]
cool! There's some conflicts with the RC branch though. Can you see if you can get those resolved? Thanks. :)

**Comment by seqoy** [comment]
I'm not sure what is the "RC" branch... Can you tell more details? Thank you jwang.

**Comment by jwang** [comment]
@seqoy - the RC branch is the development branch. They're the same. The development branch is current holding 1.0.6 RC that will be released this week, that's why I called it the RC branch. Sorry about the confusion. I should have just said there's conflicts with the current development branch.

**Comment by jwang** [comment]
Hi @seqoy Three20 1.0.6 has been released. We can add this into the 1.0.7 queue. There are conflicts with the current release, and would be helpful to get those resolved. Thanks! :)

**Comment by seqoy** [comment]
Hi @jwang, sorry I didn't have time to fix this for this release. Sure we can include on the next one. I'll work on that. Thank you.

**Comment by jwang** [comment]
hi @seqoy no worries. :)

**Comment by jwang** [comment]
Hi @seqoy - If you can get the conflicts resolved by Tuesday I want to release Release Candidates on Tuesday/Wednesday and then release it on Friday/Saturday if no issues arise from RC. :)

**Comment by seqoy** [comment]
Hi @jwang, I'll start to work to get this conflicts finished today.

**Comment by seqoy** [comment]
Hi @jwang, please check if those conflicts are fixed now.

**Comment by seqoy** [comment]
Never mind.. They still there.. Digging into.

**Comment by jwang** [comment]
@seqoy There's no conflicts right now. Thanks! I'll be pulling items in later today to get the 1.0.7 Release Candidate out. :)

**Comment by seqoy** [comment]
No GIT conflicts but some differences with the pull #474 - I'm fixing. Because we do sort of same thing in the code. I'm making sure to not broke the compatibility with @vguerci code.

**Comment by vguerci** [comment]
@seqoy, thx, sorry I did not have the time yet to give a detailed look at your pull request, but looks great so far. (right now github diff looks a bit strange to me, unrelated files changes and unresolved merge conflicts)
Ah, didn't noticed @jwang merged my pull request, thanks also!
I hope I'll have some time soon to review all of this, and maybe we could propose one unified solution. (I smell redundancies, but maybe I'm wrong)

**Comment by seqoy** [comment]
@jwang, some question. Is almost fixed now. But I'd have one issue that I can't fix yet. The improvements on the extThree20CSSStyle.xcodeproj add a lot of .h files. But when compiled the project isn't copying this new headers to the /Three20/Build/Products/three20/extThree20CSSStyle folder. That is some specific place that I must edit?

**Comment by seqoy** [comment]
Hi @vguerci, no problem. Some parts are redundant, yes. I'm merging the codes to be compatible with any project that depends from the both codes.

**Comment by vguerci** [comment]
@seqoy Maybe in Project > Build Phases > Copy Headers ?

**Comment by seqoy** [comment]
Yes, I did try to remove then all. And copy all headers on Copy Headers back, but nothing. I never can get this to work. Looping on @jwang to give us some light.

**Comment by vguerci** [comment]
Look at other three20 project settings for copy headers (public/private), and just replicate the logic. That works, but make sure to clean, of even delete `.../DerivedData/xxx` / `Build` folder... and maybe even reopen project before rebuilding... I remember some caching issues.

**Comment by seqoy** [comment]
Wow!! I did found it hidden on the bottom of the pirate bottle!! You should go under Targets > Copy Headers, select the Header file, open the "Zoom Editor" (Shift+Comman+E) and change his Role to public/private.

**Comment by seqoy** [comment]
@vguerci  I finish to merge with your code. That's some differences basically how you tell the property to the TTCSS() macro function (see StyleSheetViewController.m diffs). Because now the CSS Ruleset is one real object you can call his properties directly. My idea is to extend this object with many CSS properties we can, the macro just call the property directly. Tell me what you think.

**Comment by vguerci** [comment]
@seqoy Sorry but I'm currently pretty busy, I would be surprised if I find the time to merge latest three20 modifications in my project (including yours) this week. But from what I see, my macro was a quick (but not so dirty) approach to enhance extCSS features w/o rewriting many code like you did. Imho, now you did the job, I'm not sure this macro is really that useful and should probably removed...

**Comment by seqoy** [comment]
@vguerci no problem, some macros are useful and also when you have time to integrate a simple find/replace will be enough. @jwang we're good to go with this commit. Good job! I really enjoy to engage on this kind of "community woek" with good developers. Thanks.

**Comment by jwang** [comment]
@seqoy @vguerci - Thank you. :)

**Pull request merged**
