### PR TITLE
TTTableViewCell background color issue on iPad devices

### PR DESCRIPTION
**Pull request by aporat**
iPad table cell backgrounds aren't completely white, they have a little dark gray color background. This is an issue, as the background colors in the default style sheet are set as white. this creates a ugly white overlay if you use TTTableView text cells.

This change just change the background to clearColor, which blends nicely into the background (on both iPad & iPhone)

### CODE REVIEW

**Comment by coredream** [comment]
I see this issue as well on the iPad, and this fixes it.  But note TTThumbsViewController ends up with a black background by default since it also uses TTSTYLEVAR(backgroundColor).

**Comment by aporat** [comment]
Yeah, i had the same issue as well.

we can either solve it by creating new styles just for the tables, such as tableBackgroundColor, or by updating the existing code to make sure the text background layer are white. I rather go over the TTViewControllers updates to avoid adding new styles

comment?

**Comment by coredream** [comment]
I agree, the latter is a better solution instead of creating new styles.

**Comment by aporat** [comment]
the last commit fixes the issue with the background color in the photo controller, so it's okay to merge as far as I know..

**Comment by colinyoung** [comment]
just a bump, i'm seeing this on the iPhone 5.0 simulator and device as well.  @aporat's fix worked perfectly to fix the problem.

**Comment by aporat** [comment]
@diederich can you merge? it is a simple and important iPad fix

**Comment by diederich** [comment]
While this might have quite an performance impact, I agree the default should be clearColor. 
Devs will find this issue during performance optimization anyways and can fix/change it then.

**Pull request merged**
