### PR TITLE
Posterous fork of Three20

### PR DESCRIPTION
**Pull request by thinktopdown**
I would like to kill the Posterous fork of Three20. Please consider pulling these commits.

Eh, looks like some of commits are out of order and not consolidated. I'll make sure these are cleaner in the future.

### CODE REVIEW

**Comment by jwang** [comment]
There's a lot going on in here. Can you give me a synopsis of what the changes are?

**Comment by thinktopdown** [comment]
TTSectionDataSource
- Method for adding items

TTListDataSource
- Method for adding items
- Method for removing items

TTTextEditor
- Getter for textView

TTBaseNavigator
- Support for mailto:// URLs (need to update the query parsing method to the new one)

TTURLJSONResponse
- Should check the content-type to ensure its json before parsing

YAJL
- Was crashing some bad json. This hack skips over null values

TTURLRequest
- Getter for URLs with params

**Comment by jwang** [comment]
Awesome. Thanks. Will take a look at it in piecemeal form.

**Comment by jwang** [comment]
scheduled for 1.0.4 release. I'll be pulling this in for testing this week.

**Comment by thinktopdown** [comment]
awesome. let me know if i can help

**Comment by jwang** [comment]
someone closed this by accident?

**Comment by thinktopdown** [comment]
eh yea. hit comment & close on accident.

**Comment by jwang** [comment]
This is taking longer than I thought to pull together, but it's coming along nicely. :)

**Pull request closed without merging**
