### PR TITLE
Small cleanup

### PR DESCRIPTION
**Pull request by vguerci**
These build environment variables are no longer used in three20.

Related to facebook/three20@bb13c549e388c8da6bc79637ec28239a1bdbd821

### CODE REVIEW

**Comment by jverkoey** [comment]
This looks good, thanks! Have you tested it?

**Comment by vguerci** [comment]
Everything building fine on my side, also did some greps on `three20/` to check I wasn't forgetting references.

**Comment by jverkoey** [comment]
Sweet. I'll test it as well and then merge this change in.

**Comment by jverkoey** [comment]
Merge branch &#39;vguerci-cleanup-unused-buildenvs&#39; into development

Closed by 81b9193ef6605e1fc3282d1e1512147d748d8dde.

**Pull request closed without merging**
