### PR TITLE
Fix layout bug table image item cell

### PR DESCRIPTION
**Pull request by jverkoey**
Factored out method to choose the font and use that for height calculations and in setObject

### CODE REVIEW

**Comment by jverkoey** [comment]
Which bug is this fixing?

**Comment by diederich** [comment]
the cell uses 2 different fonts the different table items it handles, but height calculation was solely based on TTSTYLEVAR(tableSmallFont). 
To fix it, the decision which font to use was factored out and is now used in height calculation (+heightFor...) and during configuration (setObject:)

**Comment by diederich** [comment]
better commit message might be: 
[UI] Fix height calculation of TTTableImageItems'

**Comment by jverkoey** [comment]
Ah cool, that makes sense now :)

**Comment by jverkoey** [comment]
Does this commit fix any known issue?

**Comment by diederich** [comment]
was reported on IRC by dwery...

**Comment by jverkoey** [comment]
Ah cool, was just curious whether there were any issues to close, thanks!

**Comment by jverkoey** [comment]
Merge branch &#39;fix-layout-bug-tableImageItemCell&#39; into development

Closed by 2712bf09d93f30d0f5fd36a40886a25285ee8e47.

**Pull request closed without merging**
