### PR TITLE
Styled table group headers

### PR DESCRIPTION
**Pull request by savanah**
This patch allows custom styling of the headers for UITableViewStyleGrouped tables in the same way plain table group heads are styled with TTSTYLEVAR(tableHeaderTintColor)

Also adds to TTCatalog to demonstrate how it's used.

### CODE REVIEW

**Comment by vguerci** [comment]
This feature badly missing imho, thanks for submitting that pull, I'm interested by.

**Comment by jverkoey** [comment]
Looks like some stray commits made their way into this pull request. Can you `rebase -i` the branch and remove the debugging commit?

**Comment by savanah** [comment]
I rebased on the current development branch.  (Actually had some merge conflicts, which I think I merged correctly.)  I'll be issuing a new pull request shortly.

**Comment by savanah** [comment]
https://github.com/facebook/three20/pull/455

**Pull request closed without merging**
