### PR TITLE
[UI] Fix TTTextStyle shadow flipping bug

### PR DESCRIPTION
**Pull request by jeanregisser**
Hi,

This was originally submitted as part of the fixes in https://github.com/facebook/three20/pull/307
To make it easier for you to merge it, it is now based off the facebook:development branch.

Thanks.

### CODE REVIEW

**Comment by diederich** [comment]
What about factoring out that check to one of the TTCore headers and use in in the various places?

**Comment by jeanregisser** [comment]
Yes that sounds like a good idea.

**Comment by jeanregisser** [comment]
Why not merging this in?

**Comment by jwang** [comment]
That's a good question. Why did I close this. Let's re-open it and put it into next week's push. I must've thought I merged it in already.

**Pull request merged**
