### PR TITLE
extThree20XMLRPC

### PR DESCRIPTION
**Pull request by ngs**
I implemented XML-RPC request/response support extention.
Could you pull this to your master tree ?

### CODE REVIEW

**Comment by jverkoey** [comment]
Hey ngs,

Can you provide a sample application using this as well? We're building sample apps in the Three20/Articles repository now:
http://github.com/three20/Articles

Let me know if you have any questions.

**Comment by jverkoey** [comment]
Sorry, I mislinked here. We're using Three20/Samples, not Three20/Articles, for sample apps. The Articles repo is for Three20.info documentation (which could also be useful as well).

http://github.com/Three20/Samples

**Comment by ngs** [comment]
I see, I'll fork this repo and commit a sample app. Thanks.

**Comment by jverkoey** [comment]
Thanks ngs, I know this is an extra step for you. It'll be worth it, though. Not only will Three20 developers get to use your new extension, but they'll get a solid head-start into understanding how to use it in their project.

**Comment by ngs** [comment]
Hi.
I pushed my sample application at commit ngs/Samples@eafcce02df86d2c01977

**Comment by jverkoey** [comment]
Awesome, thanks ngs! For now we're going to hold off on merging this into the mainline because there will be some changes coming soon with respect to how we manage extensions.

**Comment by jwang** [comment]
Hi ngs,

Can you please do a pull request to the http://github.com/Three20/Samples repo for this?
Thanks.

**Comment by ngs** [comment]
Hi jwang.

Thank you for remind me that.
I sent a pull request to facebook.

Thanks

**Comment by jwang** [comment]
thanks. I pulled your sample app into the repo. I'll let you know on Monday what to do about the extension. Don't have an answer to that yet.

**Comment by jwang** [comment]
Hi ngs,

So the decision is to have others release extensions as their own, through their own public github accounts and submit them to the extensions gallery [Three20.info/Extensions](http://three20.info/extensions). Instead of bringing them into the main repo. This prevents increasing the size of Three20 and lets users use and develop more extensions as they see fit for their apps.

Instructions are available in the [submit link.](http://three20.info/extensions/submit)

**Comment by ngs** [comment]
Hi jwang.

I've submit my extention. http://three20.info/extension/extXMLRPC
Thank you for information.

**Pull request closed without merging**
