### PR TITLE
[UI] TTStripTab setSelectedTabIndexToCenter function added

### PR DESCRIPTION
**Pull request by aporat**
I'm not sure it's something you would want to add to the main branch, but here you go anyway :-)

This function will select a specific tab item and center that tab item on the strip tab. If i use the standard setSelectedTabIndex function, it would still select it, but the tab item will out of the scroll view..

So for example, if the strip tab has 20 items, and when the app is launched, i want to be in the 10 tab to begin with, this function will do that.

### CODE REVIEW

**Comment by jverkoey** [comment]
This commit looks really useful, thanks aporat! I have a few modification requests to make that shouldn't take too much time. Mostly just requesting documentation and separating the method into smaller methods.

**Comment by jverkoey** [comment]
Ping. Are you still interested in fixing up the methods?

**Comment by aporat** [comment]
Yes. 

I'll open another pull request when I'll work on that.

**Comment by jverkoey** [comment]
Cool, looking forward to it :) Thanks again aporat.

**Pull request closed without merging**
