### PR TITLE
Fix, missed some categories for -all_load fix

### PR DESCRIPTION
**Pull request by echamberlain**
Commit ce15efe0f521ba53f8ad24bc52403ad8ce7b2598 missed adding the fix to some categories.  Here they are.

### CODE REVIEW

**Comment by jverkoey** [comment]
Can you rebase this off of facebook:development? We've already merged the first commit in and that will make it easier to merge this update in.

Also, a minor stylistic question: my gut is saying that the `#import` should be at the top of the header files with the other imports, what do you think?

**Comment by echamberlain** [comment]
Will rebase and resubmit.

Agreed on the #import, but it was much easier to copy and paste at the bottom. :)

Since the fix is going to be adopted, I'll move it to the top.

**Comment by echamberlain** [comment]
I've moved the #import to the top.

I also moved the fix macro before the @implementation, it's easier to confirm that the fix macro is present.

**Comment by echamberlain** [comment]
This pull request is a mess, I'm not sure why so many commits are included.  I will close and resubmit.  

The new pull request is #422.

**Pull request closed without merging**
