### PR TITLE
TTDevicePlatform() function

### PR DESCRIPTION
**Pull request by aporat**
A little useful function to get a human readable string of the device's platform

### CODE REVIEW

**Comment by jwang** [comment]
sweet. Thanks!

**Comment by jwang** [comment]
@aporat - Do you think we should make this be used in [TTAvailability](https://github.com/facebook/three20/blob/development/src/Three20Core/Headers/TTAvailability.h) by adding a iOS version?

**Comment by aporat** [comment]
im not sure. 

i think TTAvailability is more about iOS version availability, while this new device model just returns the model name in a human readable string.

**Comment by aporat** [comment]
oh, and i guess the function should be named TTDeviceModelName() - similar to [[UIDevice currentDevice] model] (which returns only the basic model name)

**Comment by jwang** [comment]
that makes sense to me. :)

**Pull request merged**
