### PR TITLE
Support rfc2397 data:// URI schemes (with feedback and sample)

### PR DESCRIPTION
**Pull request by savanah**
This patch allows use of data:// URIs.

These are useful in the instance where you have a picture taken locally that's not yet sent upstream to a "real" URL. Encode the thing in a data:// URI and (with this patch) TTImages Just Work.

This commit incorporates feedback from jverkoey on an earlier pull request https://github.com/facebook/three20/pull/416 and also adds a TTCatalog demonstration.

### CODE REVIEW

**Comment by jverkoey** [comment]
Ping re: the question above.

**Comment by savanah** [comment]
(Could have sworn I answered this once before... maybe didn't hit "comment" hard enough?)

As I recall it got me out of an infinite recursion problem.  I'm unable to reproduce it now, either because something else in TT networking has changed, or because I don't remember how to reproduce.  

If the former then the extra method is a little confusing but harmless.  If the latter than someone else will figure out how to reproduce and be sad.

**Comment by jverkoey** [comment]
Cool, good to know. This looks good to me then!

**Comment by jwang** [comment]
woah. hot damn. note to self. don't press the green button.

**Comment by jverkoey** [comment]
Derp.

**Comment by jverkoey** [comment]
Can you force-push back to master and remove those changes jwang?

**Comment by jverkoey** [comment]
I can't re-open this issue for some reason; possibly a bug in the issues 2.0.

Let's definitely be double-sure to check the integration branch before auto-merging.

**Comment by jverkoey** [comment]
This is definitely a cool feature though :) Merging pull requests on the go!

**Comment by jwang** [comment]
auto-merge bad. i'll rebase master to previous commit in a few min.

**Comment by jwang** [comment]
I restored master branch. I can't re-open this because github thinks it's been merged in. @savanah can you resubmit this? Also, please target development branch and not master. :)

**Pull request merged**
