### PR TITLE
New methods in TTCSSRuleSet to retrieve attributes for Core Text formatting.

### PR DESCRIPTION
**Pull request by seqoy**
- New method <code>paragraphAlign</code> - Return an <code>CTTextAlignment</code> based on the
  <code>text_align</code>CSS property.
- New method <code>attributedStringDictionary</code> -
  Return an Dictionary with formatted attributes in order to use with
  <code>NSAttributedString</code> objects.
- Now accept the <code>font-style</code> CSS property. 
- Implement the <code>NSCopying</code> protocol. 
- New <code>coreTextFont</code> method return an Core Text Formatted Font (<code>CTFontRef</code>) 
- <code>UIFont</code> are created using Core Text formatting. So you can use real <code>bold</code> and <code>italic</code> properties and the class will pick the
  correct System Font.

### CODE REVIEW

**Comment by jwang** [comment]
Ooo. Love the NSCopying protocol implementation. Any ideas how the Core Text will work on older devices? Just a question, though we likely won't care too much in the near future.

**Comment by seqoy** [comment]
Yes, <code>NSCopying</code> is cool. <b>Core Text</b> is available since <i>iOS 3.2</i>, isn't so new. I'll put some conditionals compiler and tests to disable this specific methods, and create <code>UIFont</code> using only <i>3.1</i> code. With that I think we're covered.

**Comment by seqoy** [comment]
@jwang: Take a look now. I did separate Core Text methods under a Category. And add compiler conditions for the correct iOS.

**Comment by jwang** [comment]
There's some conflicts with the development branch that need to be resolved.

**Comment by seqoy** [comment]
Ok. I'll see that.

**Comment by jamesgpearce** [comment]
Facebook has not maintained or supported Three20 for some time, and we are closing its old and outstanding pull requests.

Many, many thanks for your support of the project. If you have any further questions, please don't hesitate to let me know.

**Pull request closed without merging**
