### PR TITLE
Fix TTFourBorderStyle not filling its bounds

### PR DESCRIPTION
**Pull request by diederich**
see #528 for the reported issue

### CODE REVIEW

**Comment by jverkoey** [comment]
Verified that this patch works. +1 for merging into development.

**Comment by diederich** [comment]
hm, missed again the closing thingy and it had no merge commit :/

closed by 1fc10171048f3a4bd3adc99b7a6da29b394f1901

**Comment by jverkoey** [comment]
Make sure you do `--no-ff`.

**Comment by diederich** [comment]
```
git merge --no-ff fix-TTFourBorderStyle 
Merge made by recursive.
 samples/TTCatalog/Classes/StyleTestController.m |    5 +++++
 src/Three20Style/Sources/TTFourBorderStyle.m    |    7 ++++++-
 2 files changed, 11 insertions(+), 1 deletions(-)
```

:/

**Comment by jverkoey** [comment]
Here's my usual flow for merging into development.

```
git checkout -b <username>-<branchname> development
git pull https://github.com/<username>/three20.git <branchname>
# Test the change. Give feedback.
# fetch updates as they are made.
# Once the request is ready to merge:
git checkout development
git merge <username>-<branchname> --no-ff
git commit --amend
# Add "Closes #<issue number>" to the merge commit
git push origin development
```

**Comment by jverkoey** [comment]
Strange.

**Comment by jverkoey** [comment]
It's possible this is weird because it was pushed locally?

**Comment by diederich** [comment]
Hm, not really sure what happened. 
Anyways, a simple git log before pushing would have shown it...

**Comment by jverkoey** [comment]
No big deal really.

**Pull request closed without merging**
