### PR TITLE
Applying the linker workaround for allowing debugging on xcode 3.2.5 to sample projects

### PR DESCRIPTION
**Pull request by savanah**

### CODE REVIEW

**Comment by jwang** [comment]
Hmm. The sample projects should also be picking up from the xcconfig files. Will take a look.

**Comment by jverkoey** [comment]
I think the problem here is that each of the sample projects has its own set of dependencies, so they weren't able to easily use the same xcconfig files. I do agree with the pull request though, so can we clean this guy up by adding the `-all_load` and `-ObjC` flags to the xcconfig files that the sample projects do share?

**Comment by jwang** [comment]
I think at some point we'll want to figure out how to handle the samples as well. If we're going to move some or all to the Three20/Samples repo, or not. Same thing with the Articles. I think we need to get rid of the Articles directory in this repo. I actually already removed it from my development repo.

**Comment by jverkoey** [comment]
+1 to the removal of the Articles folder.

As for moving all of the samples to the Three20/Samples repo, it's a good point to debate because there is merit in having the TTCatalog sample bundled with the library. Perhaps we should only have TTCatalog and TTNavigatorDemo, and move the rest to Three20/Samples?

**Comment by jwang** [comment]
Those are my thoughts as well. Keeping the TTCatalog and TTNavigatorDemo and moving the others.

**Comment by jverkoey** [comment]
Let's do it :)

**Comment by jverkoey** [comment]
In the move-over, let's go ahead and have all of the projects use `-ObjC` and `-all_load`.

**Pull request closed without merging**
