### PR TITLE
Some Core formatting utility methods

### PR DESCRIPTION
**Pull request by jverkoey**
I've been doing some log-based debugging lately and these methods have made my life a bit easier. I don't know of anything similar built in to the iOS SDK, but if there is already something like this then we can nix this pull request.

### CODE REVIEW

**Comment by jwang** [comment]
Jeff, you should check out NSLogger - https://github.com/fpillet/NSLogger, it's not meant to replace this pull request, but I figured I'd mention it.

**Comment by jverkoey** [comment]
That is _gorgeous_. I wonder whether we can build a Three20 extension for that framework?

-edit- I realize I'm being a bit hyperbolic, but that is a really awesome framework.

**Comment by jwang** [comment]
I'm sure there's a way. Just requires a bit of digging around. https://github.com/fpillet/NSLogger/wiki/Integration-with-other-products

**Comment by jverkoey** [comment]
This looks like a fun weekend project.

**Comment by diederich** [comment]
Jeff, did you check [NSStringFromCGRect and friends](http://developer.apple.com/library/ios/#documentation/uikit/reference/UIKitFunctionReference/Reference/reference.html%23//apple_ref/c/func/NSStringFromCGPoint)? (CGPoint, CGSize)

**Comment by jverkoey** [comment]
Beauty, just what I was looking for. This branch is moot then.

**Pull request closed without merging**
