### PR TITLE
TTStyledTextParser button classname

### PR DESCRIPTION
**Pull request by taknology**
Added ability to assign className property to button nodes in TTStyledText for styling buttons.

File has been linted :).

### CODE REVIEW

**Comment by taknology** [comment]
I'd be happy to. Is there a specific format in which the documentation should be added? Do you have an example?

**Comment by jverkoey** [comment]
Sure! [TTMessageController](https://github.com/facebook/three20/blob/development/src/Three20UI/Headers/TTMessageController.h) has some really fleshed-out documentation.

**Comment by taknology** [comment]
Ok. I have added basic information to the header file to indicate support for the two properties (class and href). Do I need to submit a new pull request or will the changes be incorporated since they went to the same branch?

**Comment by jverkoey** [comment]
As long as you push the commits to the same branch they'll be updated in this pull request. Can you see them above there?

**Comment by taknology** [comment]
Scratch that. I should have read a little closer.  I changed the parser header file and not the button node header file.  I'll add to button node header file and send a pull request for that file.

**Comment by jverkoey** [comment]
Ah, I could have been more clear as well, but this documentation should go in the TTStyledButtonNode.h header file I think, because that's the object that these properties will affect.

**Comment by jverkoey** [comment]
One step ahead of me :)

**Comment by taknology** [comment]
Ok.  I think we are all set now.  Changes updated and committed.

**Comment by taknology** [comment]
I think I am finally starting to understand Git

**Comment by jverkoey** [comment]
A few minor things left to do:
- We generate our API docs using Doxygen, which requires that the comment block for a class be placed immediately before the declaration of the class itself. In the commits here, the comment block has been placed before the `#import`, so Doxygen might not notice that the documentation block applies to the class. To solve this, simply move the comment block to be immediately before the `@interface` line.
- Can you provide an example in the documentation of how the attributes are specified? It might not be particularly obvious to everyone that they are pulled from the HTML being parsed. A good example would be something like:
  - <button class="likeButton" href="tt://myApp/12345?action=like">
    *
  - The resulting TTStyledButtonNode will then have:
  -   - a URL path of @"tt://myApp/12345?action=like",
  -   - and a className of @"likeButton".

**Comment by jwang** [comment]
Did those last minor things get done? I didn't see a new commit come in for them.

**Comment by taknology** [comment]
I have not had an opportunity to go back and fix the documentation issues and I don't really have time right now so I am going to go ahead and close this pull request for now.  I'll resubmit at a later time.

**Pull request closed without merging**
