### PR TITLE
Networkdelegate fix2

### PR DESCRIPTION
**Pull request by Hout**
Corrected according to Jeff's comments.
Tested ok on my app.

### CODE REVIEW

**Comment by jverkoey** [comment]
Sweet. Looks good to me. Adding it to the "reviewed" bin for someone else to sign off on :)

**Comment by jverkoey** [comment]
Ah, I just realized this is a new pull request from #501. Just a heads up, but whenever you push to the branch from which you initiated the pull request, the original pull request automatically updates itself :) Go check it out at #501.

I'm going to close this pull request because it doesn't have the full context of the conversation.

**Comment by Hout** [comment]
Sorry I am still learning git. I will continue in #501

**Comment by jverkoey** [comment]
Ah no worries, this isn't so much a git thing as one of those Github features that are unintuitive until you know about them :)

**Pull request closed without merging**
