### PR TITLE
Fix disclosure indicator calculations for table view cells

### PR DESCRIPTION
**Pull request by jverkoey**
This is the first of a series of changes to the table view architecture that will lead to better cell size calculation and control via stylesheets.

Of note: cells can now be aware of whether or not they have a disclosure indicator.

So far only the messages item has been revamped.

### CODE REVIEW

**Comment by jverkoey** [comment]
Related to #491.

**Comment by jverkoey** [comment]
Related to #522.

**Comment by dwery** [comment]
would love if this can be committed...

**Comment by jamesgpearce** [comment]
Facebook has not maintained or supported Three20 for some time, and we are closing its old and outstanding pull requests.

Many, many thanks for your support of the project. If you have any further questions, please don't hesitate to let me know.

**Pull request closed without merging**
