### PR TITLE
Issue16nib support

### PR DESCRIPTION
**Pull request by tonklon**
This is ziryanov's patch from issue #16 reformatted as a pull request for simpler integration. I reviewed the code and it looks fine to me, but I did not actually test with IB.

### CODE REVIEW

**Comment by jwang** [comment]
That's cool. There's some changes in there that are scaring me for some reason. Maybe it's lack of coffee. Going to play around with it as I have a couple of Three20 apps that use IB stuff too.

**Comment by diederich** [comment]
Awesome, thanks!

I'm just looking into the TTNibDemo to see if some examples fit in there....

**Comment by diederich** [comment]
hm, after looking into this a bit, there are some things that probably need adaption.

For a sample app and some other changes, please see https://github.com/diederich/three20/branches/three20/issue16-nibsupport (sorry, but it seems I can't send you a pull request. When trying to, I can't find you in the list to choose from.. :/)

p.s.: another thing to note is that the identing and bracket style is different

**Comment by tonklon** [comment]
I will look into this.

Nothing about bracket style is explicitly mentioned in the style guidelines, although all examples over there use the line end opening bracket. I was trusting the linter there. I will fix.

p.s.: perhaps someone could update the code style guidelines. (They do not mention the empty line before else, too)

**Comment by jwang** [comment]
Thanks @tonklon - for now, when in doubt, follow [Google's Objective-C Style Guide](google-styleguide.googlecode.com/svn/trunk/objcguide.xml)

**Comment by jamesgpearce** [comment]
Facebook has not maintained or supported Three20 for some time, and we are closing its old and outstanding pull requests.

Many, many thanks for your support of the project. If you have any further questions, please don't hesitate to let me know.

**Pull request closed without merging**
