### PR TITLE
Project Modernization with Xcode 4.2

### PR DESCRIPTION
**Pull request by sumchattering**
Should we do this.? I see you guys havent done this..Why not?

### CODE REVIEW

**Comment by aporat** [comment]
yes, definitely something we should do!

there was another pull request which targeted the master branch by mistake (#727) and included some unrelated changes, so that's why it wasn't merged.

**Comment by aporat** [comment]
strangely, the code changes aren't indent correctly, so when I open the projects from your branch, Xcode reindent the changes into the correct styling. something you can check?

**Comment by sumchattering** [comment]
My Xcode inserted the indentation by itself.Let me fix this and submit a patch.

**Comment by sumchattering** [comment]
Done.Should I merge these two commits and submit a new pull request?

**Comment by aporat** [comment]
no need. it looks great as is. tested & merged. 

it's great that you also updated the sample projects!

**Pull request merged**
