### PR TITLE
Add strong / em parsing

### PR DESCRIPTION
**Pull request by olegueret**
Pull request for issue facebook#425

### CODE REVIEW

**Comment by jverkoey** [comment]
Looks pretty simple, testing now.

**Comment by olegueret** [comment]
You are totally right, sorry for that. 
Fixed in my add-strong-em-parsing branch

**Comment by jverkoey** [comment]
Can you squash both of these commits together into one and force push this pull request? Also add a `[Style]` tag to the beginning of the commit message. I'll merge it in once you've done so. Thanks :)

**Comment by olegueret** [comment]
Done.

**Comment by jverkoey** [comment]
Awesome, thanks :)

**Comment by jverkoey** [comment]
Merge branch &#39;olegueret-add-strong-em-parsing&#39; into development

Closed by 2733e2deb6b9b292aaf6033c33f4f96f7cf7d5ed.

**Pull request closed without merging**
